---
- name: Configure LAMP and vsftpd
  hosts: worker
  become: true

#vars files added To store Secrets. Issue #3
  vars_files:
    - vault/vault.yml

  vars:
    apache_domain: example.com
    apache_home_dir: /var/www/{{ apache_domain }}
    apache_user: example
# Removed from vars and added to vars_files. Issue #3
#    apache_user_password: "Pass_123@#"
    mysql_new_user: "{{ apache_user }}"
    mysql_new_password: "{{ apache_user_password }}"
    apache_user_home_dir: /home/apache
    vsftpd_user_password: "{{ apache_user_password }}"
    vsftpd_user_home_dir: "{{ apache_user_home_dir }}"

  roles:
  - role: apache
    tags: ["apache"]
  - role: php
    tags: ["php"]
  - role: mysql
    tags: ["mysql"]
  - role: phpmyadmin
    tags: ["phpmyadmin"]
  - role: vsftpd
    tags: ["vsftpd"]


  handlers:
    - include: roles/apache/handlers.yml
    - include: roles/phpmyadmin/handlers.yml
    - include: roles/mysql/handlers.yml
    - include: roles/vsftpd/handlers.yml

  environment:
    APACHE_DOMAIN: "{{ apache_domain }}"
    APACHE_HOME_DIR: "{{ apache_home_dir }}"
    APACHE_USER: "{{ apache_user }}"
    APACHE_USER_PASSWORD: "{{ apache_user_password }}"
    MYSQL_NEW_USER: "{{ mysql_new_user }}"
    MYSQL_NEW_PASSWORD: "{{ mysql_new_password }}"
    APACHE_USER_HOME_DIR: "{{ apache_user_home_dir }}"
    VSFTPD_USER_PASSWORD: "{{ vsftpd_user_password }}"
    VSFTPD_USER_HOME_DIR: "{{ vsftpd_user_home_dir }}"

